### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by trdwll** [trdwll/ActorSpawnerPlugin#1]
- [ ] Allow specific spawn points to respawn actors after x time instead of respawning all at the same time
- [ ] Only allow a spawn point to respawn actors x times then it gets disabled
- [ ] If no characters are near the actors then despawn. (store meta in array to respawn later)

Have ideas comment them below.
